# Generated by Django 5.0.2 on 2024-02-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_AgeGrp',
            fields=[
                ('age_label', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('insert_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Federation',
            fields=[
                ('fede_id', models.SlugField(editable=False, max_length=210, primary_key=True, serialize=False)),
                ('fede_code', models.PositiveIntegerField()),
                ('fede_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='D_Localisation',
            fields=[
                ('local_id', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('code_comu', models.CharField(max_length=8)),
                ('code_qpv', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('statut_geo', models.CharField(max_length=100)),
                ('label_qpv', models.CharField(max_length=100)),
                ('label_comu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='D_Sex',
            fields=[
                ('sex_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('type_label', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='F_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_target', models.PositiveIntegerField()),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_date')),
                ('fede_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_federation')),
                ('local_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_localisation')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_type')),
            ],
        ),
        migrations.CreateModel(
            name='F_Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_target', models.PositiveIntegerField()),
                ('age_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_agegrp')),
                ('fede_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_federation')),
                ('local_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_localisation')),
                ('sex_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_sex')),
            ],
        ),
    ]
