# Generated by Django 5.0.2 on 2024-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=255)),
                ('code_qpv', models.CharField(max_length=10)),
                ('nom_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('federation', models.CharField(max_length=255)),
                ('f_1_4_ans', models.IntegerField()),
                ('f_5_9_ans', models.IntegerField()),
                ('f_10_14_ans', models.IntegerField()),
                ('f_15_19_ans', models.IntegerField()),
                ('f_20_24_ans', models.IntegerField()),
                ('f_25_29_ans', models.IntegerField()),
                ('f_30_34_ans', models.IntegerField()),
                ('f_35_39_ans', models.IntegerField()),
                ('f_40_44_ans', models.IntegerField()),
                ('f_45_49_ans', models.IntegerField()),
                ('f_50_54_ans', models.IntegerField()),
                ('f_55_59_ans', models.IntegerField()),
                ('f_60_64_ans', models.IntegerField()),
                ('f_65_69_ans', models.IntegerField()),
                ('f_70_74_ans', models.IntegerField()),
                ('f_75_79_ans', models.IntegerField()),
                ('f_80_99_ans', models.IntegerField()),
                ('f_nr', models.IntegerField()),
                ('h_1_4_ans', models.IntegerField()),
                ('h_5_9_ans', models.IntegerField()),
                ('h_10_14_ans', models.IntegerField()),
                ('h_15_19_ans', models.IntegerField()),
                ('h_20_24_ans', models.IntegerField()),
                ('h_25_29_ans', models.IntegerField()),
                ('h_30_34_ans', models.IntegerField()),
                ('h_35_39_ans', models.IntegerField()),
                ('h_40_44_ans', models.IntegerField()),
                ('h_45_49_ans', models.IntegerField()),
                ('h_50_54_ans', models.IntegerField()),
                ('h_55_59_ans', models.IntegerField()),
                ('h_60_64_ans', models.IntegerField()),
                ('h_65_69_ans', models.IntegerField()),
                ('h_70_74_ans', models.IntegerField()),
                ('h_75_79_ans', models.IntegerField()),
                ('h_80_99_ans', models.IntegerField()),
                ('h_nr', models.IntegerField()),
                ('nr_nr', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
