# Generated by Django 5.0.2 on 2024-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('postal_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
            ],
        ),
    ]
